version: '3'
services:
  mongodb24-primary:
    image: mongo:2.4
    command:
      - --replSet
      - rs0
    volumes:
      - ./mongodb24/primary/data/db:/data/db
      - ./mongodb24/primary/data/log:/var/log/mongodb
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./tmp:/tmp
    # docker-entrypoint-initdb.dが効かなかったので、healthcheckで代用
    healthcheck:
      test: mongo ./docker-entrypoint-initdb.d/init.js
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always

  mongodb24-secondary:
    image: mongo:2.4
    command:
      - --replSet
      - rs0
    volumes:
      - ./mongodb24/secondary/data/db:/data/db
      - ./mongodb24/secondary/data/log:/var/log/mongodb
    expose:
      - 27017
    restart: always
  # MongoDB 2.4のアービターは、データを持たないのでボリュームは不要
  mongodb24-arbiter:
    image: mongo:2.4
    command:
      - --replSet
      - rs0
    expose:
      - 27017
    restart: always

  mongodb4-primary:
    image: mongo:4
    volumes:
      - ./mongodb4/primary/data/db:/data/db
      - ./mongodb4/primary/data/log:/var/log/mongodb
      - ./tmp:/tmp
    ports:
      - 27019:27017
    restart: always

  mongodb8-primary:
    image: mongo:8.0.6
    volumes:
      - ./mongodb8/primary/data/db:/data/db
      - ./mongodb8/primary/data/log:/var/log/mongodb
      - ./tmp:/tmp
    ports:
      - 27020:27017
    restart: always
